kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/efficacy38/Tmp/cscc-newbie-talk/cni/bin/
        containerPath: /opt/cni/bin
  - role: worker
    extraMounts:
      - hostPath: /home/efficacy38/Tmp/cscc-newbie-talk/cni/bin/
        containerPath: /opt/cni/bin
  - role: worker
    extraMounts:
      - hostPath: /home/efficacy38/Tmp/cscc-newbie-talk/cni/bin/
        containerPath: /opt/cni/bin
networking:
  # the default CNI will not be installed
  disableDefaultCNI: true
