apiVersion: v1
kind: Endpoints
metadata:
 name: cf-loadbalancer
subsets:
 - addresses:
   - ip: 1.1.1.1
   - ip: 1.0.0.1
   ports:
   - port: 53
     protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: cf-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 5353
    protocol: UDP
