apiVersion: v1
kind: Service
metadata:
  name: whoami-loadbalancer-session
  namespace: default
spec:
  selector:
    app: whoami
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
