apiVersion: v1
kind: Service
metadata:
  name:  whoami-nodeport
  namespace: default
spec:
  selector:
    app:  whoami
  type:  NodePort
  ports:
  - name:  http
    port:  80
    nodePort: 30001
    protocol: TCP
