apiVersion: v1
kind: Service
metadata:
  name:  whoami-clusterip
  namespace: default
spec:
  selector:
    app:  whoami
  type:  ClusterIP
  ports:
  - name:  http
    port:  8080
    targetPort: 80
    protocol: TCP  # optional protocol
